// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh1CuhMTor3nA-q42-prAOtML709sQ1g0',
    appId: '1:202411656895:web:930c6065b20604eca6e80a',
    messagingSenderId: '202411656895',
    projectId: 'trable-travel',
    authDomain: 'trable-travel.firebaseapp.com',
    storageBucket: 'trable-travel.appspot.com',
    measurementId: 'G-D2HFH2116E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Av4nUlXndpUI7TFNVCA9wJpNVG6BjAk',
    appId: '1:202411656895:android:cb43ffadbff80c83a6e80a',
    messagingSenderId: '202411656895',
    projectId: 'trable-travel',
    storageBucket: 'trable-travel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6Mq5iUipIMcYPno9HYIfF0Qe9obNtBI',
    appId: '1:202411656895:ios:d24bbc31ecc7d631a6e80a',
    messagingSenderId: '202411656895',
    projectId: 'trable-travel',
    storageBucket: 'trable-travel.appspot.com',
    iosClientId: '202411656895-qv5saqp3h0mi8hqrtj32tpibotprj5n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.traveltrouble',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb6Mq5iUipIMcYPno9HYIfF0Qe9obNtBI',
    appId: '1:202411656895:ios:982224da808fcc71a6e80a',
    messagingSenderId: '202411656895',
    projectId: 'trable-travel',
    storageBucket: 'trable-travel.appspot.com',
    iosClientId: '202411656895-a9emi4i421fi1lcpbg43ueo91f97v0g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.traveltrouble.RunnerTests',
  );
}
